### ISSUE TITLE
Getting started

### ISSUE THREAD

**Issue by AtomicNess123** [nobiot/org-remark#17]
I went to the documentation but I may be a fool, I can't find how to CREATE a highlight. The documentation assumes I have created highlights in the text and teaches me how to navigate them.

**Comment by nobiot** [comment]
Maybe I should improve the documentation. The first paragraph of the section 2.1 Highlighting and Annotating in Getting Started start with this paragtaph:

> Once you have installed and set it up (Installation), Org-remark is simple to use. Select a part of text and call M-x org-remark-mark to highlight it. You will see the selected text gets highlighted.

**Comment by nobiot** [comment]
Let me know how you go :)

**Comment by AtomicNess123** [comment]
Thanks, it was my fault. :) It was very clear indeed. So as I understand, this package will create annotations and these will be stored also as extracted text in an org buffer called "marginalia.org"? What I need to know is how to remove annotations (all annotations at once or just specific ones).

**Comment by nobiot** [comment]
There is no command that remove all the highlights at once. For single highlight, you would want to use either of the two below (from the [user manual](https://nobiot.github.io/org-remark/#Other-Commands))

Command org-remark-remove
Remove the highlight at point. It will remove the highlight and the properties from the marginal notes file, but will keep the headline and annotations. This is to ensure to keep any notes you might have written intact. You can let this command DELETE the entire heading subtree for the highlight along with the annotations you have written, by passing a universal argument with C-u. If you have done so by error, you could still undo it in the marginal notes buffer, but not from within the current buffer as adding and removing overlays are not part of the undo tree.

Command org-remark-delete
Delete the highlight at POINT and marginal notes for it. This function will prompt for confirmation if there is any notes present in the marginal notes buffer. When the marginal notes buffer is not displayed in the current frame, it will be temporarily displayed together with the prompt for the user to see the notes. If there is no notes, this function will not prompt for confirmation and will remove the highlight and deletes the entry in the marginal notes buffer. This command is identical with passing a universal argument to ‘org-remark-remove’.

**Comment by AtomicNess123** [comment]
Thanks, all clear now! I suppose that the marginalia buffer name + location are configurable?

**Comment by AtomicNess123** [comment]
Thanks. This package is very similar to org-noter. It would be great if you could highlight the differences in the README.

**Comment by nobiot** [comment]
What is the similarity? I don't read PDF on Emacs so I have no idea.

**Comment by AtomicNess123** [comment]
I was wrong, as I understand now [org-noter](https://github.com/weirdNox/org-noter) can't be used to take notes of org-mode files, but it does the same that org-remark but with PDFs and other types of docs.
