### ISSUE TITLE
Could notes be saved within the annotated file?

### ISSUE THREAD

**Issue by ericsfraga** [nobiot/org-remark#18]
This package looks very nice.
I am not a big fan of the annotations being in a separate file as it makes sharing difficult. I am also curious what happens when you have more than one org file being annotated in the same directory. I wonder whether it would be possible to have the annotations stored within the same file, e.g. as a separate top level heading?

**Comment by nobiot** [comment]
It seems to be a frequently asked question. I will consider adding this to the user manual. Thank you.

**Comment by ericsfraga** [comment]
Ah, okay, this sounds good. Thank you. I will give this a try.
I do understand your point of needing an external file for non-org files but I don't think I have any non-org files. ;-)

**Comment by nobiot** [comment]
Oh, wait a sec. I may have found a bug in this setup. 
In principle, this should be how it should work (and it does) but the save loops too many times. Let me come back...

**Comment by ericsfraga** [comment]
Ok, no worries. I won't be trying this until next week in any case. I will wait until you confirm it's working fine.Thank you!

**Comment by nobiot** [comment]
I think this [commit](https://github.com/nobiot/org-remark/commit/916924ad293a5ae710b7fa20d8e4124989881d65) fixed the bug.

**Comment by nobiot** [comment]
@ericsfraga 
Have you had a chance to try this?
I'd love to have some feedback before I bump up the version to release the latest version on ELPA.
No worries if you don't have time to do this :)

**Comment by ericsfraga** [comment]
Not yet, sorry. It's on my todo list; I'll see if I can get to it today or else tomorrow.

**Comment by ericsfraga** [comment]
Okay, I made some time. Seems to work just fine, saving notes to the same file. However, this does cause some issues (e.g. local file variables, which I use a lot) so maybe I need to rethink the benefits of this approach. A separate file may indeed be the right way to go.

In any case, thank you for addressing this point.

**Comment by ericsfraga** [comment]
I had the impression that there were limitations on how far from the end of the document file local variables can be. If that were the case then, if you take too many notes (and I am using org-remark on a book I'm writing so potentially a lot of notes), the local file var section will be too far away. However, going through the documentation for file local variables, I do not see any mention of a limit so what you say above may indeed be perfectly fine. In any case, I've gone with the separate file for now but may play more later.
Thank you.
