### ISSUE TITLE
[Feature Request] Delete notes when highlight is removed if the notes are empty

### ISSUE THREAD

**Issue by darcamo** [nobiot/org-remark#21]
I understand the importance of having separated `org-remark-remove` and `org-remark-delete` functions, since one might want to remove the highlight without deleting any associated notes.

I also assume that when I manually delete the highlighted text (for instance, using something like `kill-whole-line`) org-remark calls `org-remark-remove` to delete the properties in the notes file, while keeping any notes there intact.

In both cases (calling `org-remark-remove` or manually deleting the highlighted text) it would be nice if org-remark deleted the whole heading in the notes file like `org-remark-delete` does, provided that there are no notes there. This would help keeping the notes file clean.

**Comment by nobiot** [comment]
@darcamo Thank you for your feature request.

I think it makes sense.  

Let me have some time. Hopefully it will be a matter of a couple of weekends. First, I would like to publish the current version to ELPA (it's currently only available in ELPA-devel), and then refactor remove/delete to allow for the change to implement this feature.

Do you find Org-remark working fine for you otherwise? I'd love to have some feedback before I bump up the version to release it on ELPA :)

**Comment by darcamo** [comment]
I haven't used org-remark very much yet. I actually just installed it yesterday.

My main use-case is to just be able to highlight parts of my org-roam notes (to indicate that I should go back and improve that part later). Binding `org-remark-mark` to something easy solves this and deleting empty notes when the highlight is removed will avoid cluttering the notes file.

I think org-remark could also useful in programming buffers, but only for short term temporary highlights and without any annotations. Differently from my org-roam notes which are edited only by me and always in Emacs, source code is edited by other people (sometimes by me outside Emacs), which breaks the highlights. Even an automatic source code formatter run in a git pre-commit would break the highlights. But I still think it's good that org-remark does not change the actual text file, even if the highlights might be more fragile to these changes.

One thing that immediately came to mind when I started using org-remark is the similarity with [org-noter](https://github.com/weirdNox/org-noter). But org-noter only works with PDF files. I think that org-remark could be an excellent alternative when dealing with ebooks in other formats such as epub. I tried it when viewing an ebook with the  [nov](https://depp.brause.cc/nov.el/) package, it fails at the moment due to `buffer-file-name` returning nil.

**Comment by nobiot** [comment]
@darcamo Thank you for your detailed feedback.

I don't really program other than for Elisp for Emacs, so thanks for the insight. I don't think I can support changes made outside Emacs with Org-remark.

With Nov.el, Org-noter's README says it can support it, so perhaps you could try it, instead of Org-remark.

**Comment by sati-bodhi** [comment]
Regarding @darcamo's `nov` epub-reader support request above, I find: 

```elisp
(defun org-remark-source-find-file-name ()
  "Assumes that we are currently in the source buffer.
Returns the filename for the source buffer.  We use this filename
to identify the source buffer in all operations related to
marginal notes."
  (let ((filename (or buffer-file-name
                      (run-hook-with-args-until-success
                       'org-remark-source-find-file-name-functions))))
    filename))
```

It seems to me `org-remark-source-find-file-name-functions` can be customized to make use of, say, in-built `org-noter` functions that return the `epub` source file referenced by the `org-noter--session`.

Here is my preliminary setup:

```elisp
  ;; compatibility with org-noter
  (defun org-noter-get-epub-source ()
    "Returns the path of the epub source from which the present session is initiated."
    (org-noter--session-property-text org-noter--session))

  (setq org-remark-source-find-file-name-functions '(org-noter-get-epub-source))
```

I was able to *highlight* and *add notes* to `epub` files viewed in `nov` with this simple setup. 

Only issue is, the notes file, `marginalia.org` in this case is stored at the temporary location where the  `session.10e8598b3bc0292941167275239838173700000033310232` instance lives - `~/.emacs.d/.local/cache` - by default. 

Tried setting `org-remark-notes-file-name` to an absolute path, but wasn't able to change this behavior. 

Any leads?

**Comment by sati-bodhi** [comment]
Since this is separate from the main topic of this issue, I have opened a new issue for it.

**Comment by nobiot** [comment]
The feature originally requested is this: Delete notes when highlight is removed if the notes are empty. This feature is now available in GNU-devel ELPA (will be available in GNU ELPA after a few weeks/months).

There is a user option to toggle this feature on/off (default is off). Refer to the user manual:
https://nobiot.github.io/org-remark/#How-to-Remove-and-Delete-Highlights.

Or evaluate this in Emacs `(info "(org-remark) How to Remove and Delete Highlights")` for Info documentation.

Closing this feature request (finally!). Let me know if you have issues or questions.
