### ISSUE TITLE
Not all highlights loaded when marginalia.org file does not show all the headlnies

### ISSUE THREAD

**Issue by zhewy** [nobiot/org-remark#22]
**Describe the bug**
creating a highlight of a file requiring differnt encoding will cause issues with reload of highlights. 

**To Reproduce**
1. refer to files [test files.zip](https://github.com/nobiot/org-remark/files/8116585/test.files.zip)
2. if file open of asdf.org, expect highlights of words "ipsum is" and "‘Rautāwhiri’" (as setup per marginalia.org)
3. it doesn't. 
4. to fix, open up marganalia file, the go back to text file buffer, toggle org-remark-mode. highligts then become visible. if try and kill buffer marginalia again, prompts to save particular encoding. once selected, bug can be reproduced again.

**Comment by zhewy** [comment]
maybe another variant on the same problem: 
[asdf.zip](https://github.com/nobiot/org-remark/files/8130700/asdf.zip)

1. if i open reading.org directly, the highlights don't load "properly". 
2. if i first open marginalia.org and then open reading.org right afterwards, highlights also don't load "properly".
3. if i open marginalia.org, then expand the headings, then open reading.org file - the highlights load as expected

**Comment by nobiot** [comment]
Thank you for reporting this issue.

I'm struggling to reproduce the issue; I can simply visit the `asdf.org` and get this (I didn't visit `marginalia.org` before).
How can you have different encoding setup for different files?

I just have this in my customizing: `current-language-environment "UTF-8"`.

![image](https://user-images.githubusercontent.com/12507865/155563643-93f45db8-a1eb-4ff0-9131-5bceb03f347a.png)

**Comment by zhewy** [comment]
perhaps it's not to do with encoding after all.. i've been getting this behaviour on other 'standard' encoded files.

work-around is to have marginalia.org and expanded (as below)..

my experience when opening the same asdf.org:
![image](https://user-images.githubusercontent.com/998072/155801877-b725979a-2090-4135-a2ce-3cbdcf969c4d.png)
- left window (1) is result of "org-remark-open". note this doesn't show text.
- window in middle (2) is file.
- window on right (3) is marginalia.org
if i toggle org-remark-mode from middle window with marginalia.org collapsed as shown, the wrong highlights are shown and window(1) doesn't display properly as shown.

if` i expand marginalia.org to show as follows and toggle org-remark-mode on/off:
![image](https://user-images.githubusercontent.com/998072/155802521-c270e732-39cb-47ba-91ec-43d779e2a210.png)
- window (2) now shows right highlight
- on org-remark-open the right text is now shown.

emacs version:
- replicated on 28 & 27.

**Comment by nobiot** [comment]
I see. Thank you. I can reproduce the issue. 

Try the new commit #[97239d7](https://github.com/nobiot/org-remark/commit/97239d7beda4c9934c513452957e9e9ad76bc44e) -- if you don't use Git, it should be synced with ELPA-devel at some point soon.  I'd appreciate your testing it.

I'll wait for your response before I bump the version for ELPA. Let me know.

**Comment by zhewy** [comment]
commit #[97239d7](https://github.com/nobiot/org-remark/commit/97239d7beda4c9934c513452957e9e9ad76bc44e)
fixes issue. 
thank you for all your work!!
