### ISSUE TITLE
org-remark breaks export to pdf, html

### ISSUE THREAD

**Issue by QMeqGR** [nobiot/org-remark#23]
If I enable org-remark and try to export /some/ org files to pdf or html it fails with an error: "Wrong type argument: stringp, nil". I tried isolating parts of the files and I think (not 100% certain) that it has something to do with line(s) like:

#+INCLUDE: "./P4350_course.org::#Syllabus" :only-contents t

If I don't load org-remark everything works fine.

The backtrace on error is:

Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  expand-file-name(nil)
  file-relative-name(nil)
  org-remark-source-get-file-name(nil)
  org-remark-highlights-get()
  org-remark-highlights-load()
  org-remark-mode()
  run-hooks(change-major-mode-after-body-hook text-mode-hook outline-mode-hook org-mode-hook)
  apply(run-hooks (change-major-mode-after-body-hook text-mode-hook outline-mode-hook org-mode-hook))
  run-mode-hooks(org-mode-hook)
  org-mode()
  org-link-open-from-string("[[elisp:(org-latex-export-to-pdf nil t)][PDF]]")
  org-open-at-point-global()
  funcall-interactively(org-open-at-point-global)
  call-interactively(org-open-at-point-global)
  #f(compiled-function (&optional arg) "Open link, timestamp, footnote or tags at point.\n\nWhen point is on a link, follow it.  Normally, files will be\nopened by an appropriate application.  If the optional prefix\nargument ARG is non-nil, Emacs will visit the file.  With\na double prefix argument, try to open outside of Emacs, in the\napplication the system uses for this file type.\n\nWhen point is on a timestamp, open the agenda at the day\nspecified.\n\nWhen point is a footnote definition, move to the first reference\nfound.  If it is on a reference, move to the associated\ndefinition.\n\nWhen point is on a headline, display a list of every link in the\nentry, so it is possible to pick one, or all, of them.  If point\nis on a tag, call `org-tags-view' instead.\n\nOn top of syntactically correct links, this function also tries\nto open links and time-stamps in comments, node properties, and\nkeywords if point is on something looking like a timestamp or\na link." (interactive "P") #<bytecode 0x61a3bdf87b4e3f8>)(nil)
  ad-Advice-org-open-at-point(#f(compiled-function (&optional arg) "Open link, timestamp, footnote or tags at point.\n\nWhen point is on a link, follow it.  Normally, files will be\nopened by an appropriate application.  If the optional prefix\nargument ARG is non-nil, Emacs will visit the file.  With\na double prefix argument, try to open outside of Emacs, in the\napplication the system uses for this file type.\n\nWhen point is on a timestamp, open the agenda at the day\nspecified.\n\nWhen point is a footnote definition, move to the first reference\nfound.  If it is on a reference, move to the associated\ndefinition.\n\nWhen point is on a headline, display a list of every link in the\nentry, so it is possible to pick one, or all, of them.  If point\nis on a tag, call `org-tags-view' instead.\n\nOn top of syntactically correct links, this function also tries\nto open links and time-stamps in comments, node properties, and\nkeywords if point is on something looking like a timestamp or\na link." (interactive "P") #<bytecode 0x61a3bdf87b4e3f8>))
  apply(ad-Advice-org-open-at-point #f(compiled-function (&optional arg) "Open link, timestamp, footnote or tags at point.\n\nWhen point is on a link, follow it.  Normally, files will be\nopened by an appropriate application.  If the optional prefix\nargument ARG is non-nil, Emacs will visit the file.  With\na double prefix argument, try to open outside of Emacs, in the\napplication the system uses for this file type.\n\nWhen point is on a timestamp, open the agenda at the day\nspecified.\n\nWhen point is a footnote definition, move to the first reference\nfound.  If it is on a reference, move to the associated\ndefinition.\n\nWhen point is on a headline, display a list of every link in the\nentry, so it is possible to pick one, or all, of them.  If point\nis on a tag, call `org-tags-view' instead.\n\nOn top of syntactically correct links, this function also tries\nto open links and time-stamps in comments, node properties, and\nkeywords if point is on something looking like a timestamp or\na link." (interactive "P") #<bytecode 0x61a3bdf87b4e3f8>) nil)
  org-open-at-point()
  org-open-at-mouse((mouse-2 (#<window 3 on P4350_course.org> 1193 (409 . 612) 216533407 nil 1193 (24 . 14) nil (1 . 24) (17 . 42))))
  funcall-interactively(org-open-at-mouse (mouse-2 (#<window 3 on P4350_course.org> 1193 (409 . 612) 216533407 nil 1193 (24 . 14) nil (1 . 24) (17 . 42))))
  call-interactively(org-open-at-mouse nil nil)
  command-execute(org-open-at-mouse)

**Comment by nobiot** [comment]
Thank you. I will need to spend some time to look into this issue.
Can I ask one thing?

If you removed `#+INCLUDE: "./P4350_course.org::#Syllabus" :only-contents t`, do you still get the error when `org-remark` is enabled? I am suspecting it might be related to the include function, which might not play nice with `org-remark`.

**Comment by QMeqGR** [comment]
Thanks for the quick reply! 

Indeed, if I remove the #+include statements the export works when I export by hand (C-c C-e ...) or directly with org-latex-export-to-pdf. However I use clickable links in the document to do this like: [[elisp:(org-latex-export-to-pdf nil t)][PDF]] and I get the same error when I click this link. (But the export will work if I issue it by hand.)

I have attached the org file so you can have a look.
[course.txt](https://github.com/nobiot/org-remark/files/8134306/course.txt)

**Comment by nobiot** [comment]
Is it possible for you to share with a minimal reproducible file and step-by-step instruction, please?

I commented out all the `#+INCLUDE`  and `#+LATEX_HEADER` -- I don't have the source files to include, and I don't use `latex` let alone `xelatex`. I installed `tex-live` so that I can use `pdflatex` But I still get the following error when I tried exporting your `course.txt` into a PDF file.

I have no way to install all these `*.sty` files -- I need none of them; and I don't even have sufficient knowledge in latex to use them properly.

```
This is pdfTeX, Version 3.14159265-2.6-1.40.21 (TeX Live 2020/Debian) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
(.//course.tex
LaTeX2e <2020-10-01> patch level 4
L3 programming layer <2021-01-09> xparse <2020-03-03>
(/usr/share/texlive/texmf-dist/tex/latex/base/article.cls
Document Class: article 2020/04/10 v1.4m Standard LaTeX document class
(/usr/share/texlive/texmf-dist/tex/latex/base/size11.clo))
(/usr/share/texlive/texmf-dist/tex/latex/base/inputenc.sty)
(/usr/share/texlive/texmf-dist/tex/latex/base/fontenc.sty)
(/usr/share/texlive/texmf-dist/tex/latex/graphics/graphicx.sty
(/usr/share/texlive/texmf-dist/tex/latex/graphics/keyval.sty)
(/usr/share/texlive/texmf-dist/tex/latex/graphics/graphics.sty
(/usr/share/texlive/texmf-dist/tex/latex/graphics/trig.sty)
There is no way for me to fix the latex issue
(/usr/share/texlive/texmf-dist/tex/latex/graphics-cfg/graphics.cfg)
(/usr/share/texlive/texmf-dist/tex/latex/graphics-def/pdftex.def)))
(/usr/share/texlive/texmf-dist/tex/latex/tools/longtable.sty)

! LaTeX Error: File `wrapfig.sty' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: sty)

Enter file name: 
! Emergency stop.
<read *> 
         
l.8 \usepackage
               {rotating}^^M
!  ==> Fatal error occurred, no output PDF file produced!
Transcript written on .//course.log.

```

**Comment by QMeqGR** [comment]
Please forgive me, I should have thought of that. I have reduced the file down to everything below the dashed line. Just the property drawer and the include.

org-version: 9.5.2 and 9.6snapshot both give the error
emacs: 29.0.50

------------------------------------------------

:properties:
:EXPORT_FILE_NAME: ./junk
:OUTPUT_VIEW: [[elisp:(org-latex-export-to-pdf nil t)][PDF]]
:END:
#+INCLUDE: "./minimal.org" :only-contents t

**Comment by nobiot** [comment]
@QMeqGR 
I have managed to install `wrapfig.sty` via the `texlive-latex-extra` package on Ubuntu.

How do I reproduce the error with `org-remark`?

I created a `minimal.org` like this below with a highlight with `org-remark`.
```
Please forgive me, I should have thought of that. I have reduced the file down to everything below the dashed line. Just the property drawer and the include.

org-version: 9.5.2 and 9.6snapshot both give the error
emacs: 29.0.50
```

![Screenshot from 2022-02-27 08-44-20](https://user-images.githubusercontent.com/12507865/155873631-36e41a08-6a6f-4aa9-bd24-c94f8ddc1b04.png)


I also added a highlight in `course.org`, with the content being your minimal example.

I then click on the `PDF` link; I get the following error:

![Screenshot from 2022-02-27 08-43-56](https://user-images.githubusercontent.com/12507865/155873406-78a9ec33-3931-4291-8fd0-2b211468978a.png)

If I call `C-c C-e` and `l o` to produce a PDF file, the PDF file gets generated

![Screenshot from 2022-02-27 08-41-53](https://user-images.githubusercontent.com/12507865/155873465-2360d3e3-d7de-4956-b9ec-7c8a52d6d0b0.png)

Now... To fix the "before the first headline error", I added a headline to `course.org` like this:

![Screenshot from 2022-02-27 08-50-22](https://user-images.githubusercontent.com/12507865/155873592-b077435e-bd4f-4393-9358-660d2b5a3f43.png)

I have no problem generating a `junk.pdf`:

![Screenshot from 2022-02-27 08-50-35](https://user-images.githubusercontent.com/12507865/155873598-b183dc22-13ae-4393-a009-bf8857fd08a2.png)

**Comment by nobiot** [comment]
I have also tried with no user configuration. Just installed `org-remark` from ELPA. I have no problem producing `junk.pdf`.

![Screenshot from 2022-02-27 08-59-10](https://user-images.githubusercontent.com/12507865/155873916-091d9483-d2b7-4f74-a1cd-2c45ab726780.png)

**Comment by nobiot** [comment]
Perhaps it might help you if you upgraded `org-remark` to the latest?

**Comment by QMeqGR** [comment]
I upgraded to the latest org-remark and the error still persists. To get the error I just issue

M-x org-html-export-to-html   or
M-x org-latex-export-to-pdf

or clicking the in-buffer link.

But ... I may have found the problem. It is the hook line I had in my org-remark init section.

(add-hook 'org-mode-hook 'org-remark-mode)

If I comment this line out the error is gone. So if I export either html or pdf (without being in org-remark-mode) it works. Then, even if I enable org-remark-mode in the buffer, exporting still works. 
Can you reproduce this with the minimal.org?

Here is my org-remark init: (verbatim from the github site except for the hook line)

(use-package org-remark
  :ensure t)
;; (add-hook 'org-mode-hook 'org-remark-mode)
(require 'org-remark-convert-legacy)
(require 'org-remark-global-tracking)
(org-remark-global-tracking-mode +1)
;; Key-bind `org-remark-mark' to global-map so that you can call it
;; globally before the library is loaded.
(define-key global-map (kbd "C-c n m") #'org-remark-mark)
;; The rest of keybidings are done only on loading `org-remark'
(with-eval-after-load 'org-remark
  (define-key org-remark-mode-map (kbd "C-c n o") #'org-remark-open)
  (define-key org-remark-mode-map (kbd "C-c n ]") #'org-remark-view-next)
  (define-key org-remark-mode-map (kbd "C-c n [") #'org-remark-view-prev)
  (define-key org-remark-mode-map (kbd "C-c n r") #'org-remark-remove))

**Comment by nobiot** [comment]
Yes, thank you. 
It should be fixed with [](https://github.com/nobiot/org-remark/commit/7ab876fd7d6c9574f46114078a16feb259310101)[7ab876f](https://github.com/nobiot/org-remark/commit/7ab876fd7d6c9574f46114078a16feb259310101). If you don't use Git, ELPA-devel should be updated soon. 

I'll bump the version to update ELPA a little later; need to update documentation for this fix and another I have done recently.

**Comment by QMeqGR** [comment]
Your fix works for me. Thank you!
