### ISSUE TITLE
(setq org-remark-notes-file-name 'org-remark-notes-file-name) not working

### ISSUE THREAD

**Issue by AtomicNess123** [nobiot/org-remark#26]
I am using `(setq org-remark-notes-file-name 'org-remark-notes-file-name)` to change the file name "marginalia" to the individual name of my buffer + _notes.org. But it is not working. I think this could be a bit better explained in the readme. Thanks!

**Comment by nobiot** [comment]
Hi @AtomicNess123 

Have you had a chance to look at the user manual? 
This [section](https://nobiot.github.io/org-remark/#How-to-Change-Where-Marginal-Notes-File-is-Saved) "3.3.3 How to Change Where Marginal Notes File is Saved" is intended to describe a couple of typical use cases.

> The location of the marginal notes file is specified by user option org-remark-notes-file-name and its default is “marginalia.org”. This means the marginal notes file will reside in the same directory as the source files as a separate file. 
>
> If you use the customize command to customize org-remark-notes-file-name, you will have an option to choose a ‘File’ or ‘Function’ (customization group org-remark).
> ...
> If you would like to dynamically change the location based on the file and various different conditions, select the function as an option. The default function is org-remark-notes-file-name-function. It adds ‘-notes.org’ as a suffix to the source file’s name without the extension. For example, for a file named ‘my-main-file.txt’, Org-remark will store highlights in ‘my-main-file-notes.org’. You can create your own function and use it. 

I believe it's easy to use `customize` and see the options to select from. If you prefer to use `setq`, you can put something like this:

```
(setq org-remark-notes-file-name
      #'org-remark-notes-file-name-function)
```

**Comment by AtomicNess123** [comment]
Thanks. I had tried that but I get: `Symbols function definition is void: org-org-remark-create`.
Also, there doesn't seem to be a variable called `org-remark-notes-file-name`, but `org-remark-notes-file-path` instead.

**Comment by AtomicNess123** [comment]
Thanks! One question though: what is the difference between setting:
`(setq org-remark-notes-file-path #'org-remark-notes-file-path-function)`
and
`(setq org-remark-notes-file-name #'org-remark-notes-file-name-function)`

They seem to have the same behaviour.

**Comment by nobiot** [comment]
They are the same. 

“-path” is an old name which I changed to “-file-name” to align with the GNU convention — I got the advice from Emacs mailing list. 

Technically, the former is made an alias of the latter to keep backward compatibility.
