### ISSUE TITLE
prompt for 'org-remark-hidden value:' on saving buffer

### ISSUE THREAD

**Issue by mooseyboots** [nobiot/org-remark#28]
hi, i'm new to org-remark, and i'm puzzled by this prompt i get on saving.

i can't see in your code where such a prompt is given, nor can i understand how to even provide it with a value that it will accept.

looks like it is coming from somewhere in `org-remark-highlight-save`.

not sure if i need to set things up a little more for it to work right?

**Comment by mooseyboots** [comment]
dang, that's bad news. i was hoping had just missed a step of set up and was being prompted to do it.

it appears as a minibuffer prompt, text as mentioned in the title:
```
org-remark-hidden value: 
```

looks like the prompt is from `org-set-property`, which your `org-remark-notes-set-properties` calls.

if you have a minimal setup that gets `org-remark` running it'd be helpful, starting from emacs -Q and manually trying to add everything needed is painful. (running `-mark` fails with a complaint about `org-collect-properties` even tho org is loaded.)

looks like i actually get two different/related errors:

if i open an org file with no notes, add a note with `-mark` open it with `-open`, add some text to the note, switch back to the org file, save it, no problems. if i first run `-toggle`, then trivially edit the file and save, i get: 

``` elisp
Debugger entered--Lisp error: (wrong-type-argument sequencep t)
  org-set-property("org-remark-hidden" t)
  org-remark-notes-set-properties(143 149 (org-remark-hidden t org-remark-face org-remark-highlighter org-remark-id "1d216083" "org-remark-label" "nil" face nil "org-remark-link" "[[file:my-file.org::7]]"))
  org-remark-highlight-save("/path/to/file/my-file.org" 143 149 (org-remark-hidden t org-remark-face org-remark-highlighter org-remark-id "1d216083" "org-remark-label" "nil" face nil "org-remark-link" "[[file:my-file.org::7]]"))
  org-remark-save()
  run-hooks(after-save-hook)
  basic-save-buffer(t)
  save-buffer(1)
  funcall-interactively(save-buffer 1)
  call-interactively(save-buffer nil nil)
  command-execute(save-buffer)
```
if i then run `-toggle` again, i get the prompt. if i enter nothing in the prompt, just hit RET, i get
```
org-remark-notes-set-properties: Wrong type argument: sequencep, org-remark-highlighter
```
i don't know how your code works at all, not really these bits of org, so i'm in the dark.

**Comment by nobiot** [comment]
Thank you. I can reproduce it now.
It's a defect in the way `-toggle` function works. If you avoid it for now, the error should not happen.
I will need to spend more time look into it for a fix -- tried, but could not get it done. Still working out a way.

**Comment by nobiot** [comment]
The latest commit should fix the issue. The ELPA repository should also be updated soon. Let me know if the issue persists (feel free to re-open. Thank you for reporting the issue. Toggle never worked properly before your report.

**Comment by mooseyboots** [comment]
glad it got sorted. I'll try out the elpa version when it updates.

**Comment by nobiot** [comment]
Thanks. Should be version 1.0.5.
