### ISSUE TITLE
Version 1.0.4: when does org-remark-link use an absolute path, and when not

### ISSUE THREAD

**Issue by ouboub** [nobiot/org-remark#29]
Hi

I start to use the package frequently, and just found out that 
org-remark-mark, either inserts 
** *Ejercicio 1 (Rutinas de Matlab y un método adaptativo): 2 puntos*
   :PROPERTIES:
   :org-remark-beg: 253
   :org-remark-end: 187
   :org-remark-id: d01909f8
   :org-remark-label: nil
   :org-remark-link: [[file:annu_examen_mayo2022_text.m::13]]
   :END:

or 

**  ode45 
   :PROPERTIES:
   :org-remark-beg: 1026
   :org-remark-end: 1018
   :org-remark-id: aedfe90e
   :org-remark-label: nil
   :org-remark-link: [[file:~/ALLES/HGs/tex/vorlesungen/HGAnnu/Klausuren/Arbeit22/Mayo/Matlab/ExamenMatlabStudAnnu22/G1/Student_4004945_assignsubmission_file_/annu_examen_mayo2022_text.m::33]]
   :END:

I need an absolute path, not a relative one

how can I achieve this?
regards
Uwe Brauer

**Comment by ouboub** [comment]
I checked I have set
org-link-file-path-type  is set to absolute
but the path is org-remark-make sets is relative

**Comment by ouboub** [comment]
it seems that (org-remark-source-file-name 'abbreviate-file-name) solves the problem?

**Comment by nobiot** [comment]
Yes. `(org-remark-source-file-name 'abbreviate-file-name)`. You can also use other functions -- see `customizing` or docstring of the variable.  I will consider if I can improve the user manual.

**Comment by nobiot** [comment]
[This section](https://nobiot.github.io/org-remark/#How-to-Use-Relative-or-Absolute-File-Names-for-Links-in-Marginal-Notes-File) of the user manual was meant to be for the question you had. Please advise if you have some ideas to make things clearer.

**Comment by ouboub** [comment]
>>> "NO" == Noboru Ota ***@***.***> writes:

> [This
> section](https://nobiot.github.io/org-remark/#How-to-Use-Relative-or-Absolute-File-Names-for-Links-in-Marginal-Notes-File)
> of the user manual was meant to be for the question you had. Please
> advise if you have some ideas to make things clearer.

That part is sufficient clear. However I have installed the package via melpa and Emacs package manager, and I cannot find this manual in the corresponding directory of where the package is installed.


-- 
I strongly condemn Putin's war of aggression against the Ukraine.
I support to deliver weapons to Ukraine's military. 
I support the ban of Russia from SWIFT.
I support the EU membership of the Ukraine.

**Comment by nobiot** [comment]
If you use the built-in `package.el`, the user manual should be available automatically via `C-h i`. I do this myself for my Windows PC and Linux machine. 

If this is not the case, your Emacs may not be properly set up (?) I never had to do anything extra; I just install or compile Emacs, and this just works for both of my machines.
