### ISSUE TITLE
org-remark-link descripton

### ISSUE THREAD

**Issue by ouboub** [nobiot/org-remark#30]
hi

in my setting org-remark-mark
add an entry to the marginalia.org of the form
** \NiceMatrixOptions{letter-for-dotted-lines=V}
   :PROPERTIES:
   :org-remark-beg: 472
   :org-remark-end: 427
   :org-remark-id: 6860f5d7
   :org-remark-label: nil
   :org-remark-link: [[file:~/ALLES/HGs/tex/vorlesungen/MasterIQ/HGMaster-IQ/Folien/Examen/test.m::22]]
   :END:

could it be please 
[[file:~/ALLES/HGs/tex/vorlesungen/MasterIQ/HGMaster-IQ/Folien/Examen/test.m::22][link1]]
or something similar? or say
[[file:~/ALLES/HGs/tex/vorlesungen/MasterIQ/HGMaster-IQ/Folien/Examen/test.m::22][linenumer::22]]

BTW what is org-remark-label supposed to do?
Uwe Brauer

**Comment by ouboub** [comment]
I changed the function 
(defun org-remark-highlight-save (filename beg end props &optional title)
so that the link now contains a description that is a combination of its file name and the current line.
it is quite primitive, but it works, if you are interested I can send you a patch

**Comment by nobiot** [comment]
Thank you. What does the link look like after your change?

`org-remark-label` is to record the type of different pens. `nil` means you have used the default pen.
I now realize I missed this part in the user manual. I'll see how I can add the information. Thank you for pointing this out.

**Comment by ouboub** [comment]
>>> "NO" == Noboru Ota ***@***.***> writes:

> Thank you. What does the link look like after your change?
> `org-remark-label` is to record the type of different pens. `nil` means you have used the default pen.

By pen how mean the way the link is highlighted? I have to say that I am not sure I understand what you mean by pen.


> I now realize I missed this part in the user manual. I'll see how I can add the information. Thank you for pointing this out.

-- 
I strongly condemn Putin's war of aggression against the Ukraine.
I support to deliver weapons to Ukraine's military. 
I support the ban of Russia from SWIFT.
I support the EU membership of the Ukraine.

**Comment by ouboub** [comment]
> Thank you. What does the link look like after your change?

I opted for filename(without-extension)-X

Where X is the line-number

Another option would be filename(without-extension)-line-X

I will send a screenshot

-- 
I strongly condemn Putin's war of aggression against the Ukraine.
I support to deliver weapons to Ukraine's military. 
I support the ban of Russia from SWIFT.
I support the EU membership of the Ukraine.

**Comment by ouboub** [comment]
![remark-filenam-line](https://user-images.githubusercontent.com/5957203/168420416-e88aed61-e31c-4e68-9ffa-1a85face856e.png)

**Comment by nobiot** [comment]
> By pen how mean the way the link is highlighted? I have to say that I am not sure I understand what you mean by pen.

I invite you to watch an [introductory video](https://youtu.be/c8DHrAsFiLc)  as noted in README. I showcase the capability to use and create your own pens. It's also described in this part of the [user manual](https://nobiot.github.io/org-remark/#Create-Your-Own-Highlighter-Pens).

**Comment by nobiot** [comment]
Claomg.
