### ISSUE TITLE
buffers save 8 times on save

### ISSUE THREAD

**Issue by mooseyboots** [nobiot/org-remark#33]
after adding a remark, on saving, my buffer and my notes buffer save around 8 times.

i only have really basic remarks, and only a few.

i also have an undo tree buffer being saved. i'm not sure if it is interfering with `org-remark`.

has anyone else seen this?

**Comment by nobiot** [comment]
I think it is the way it is designed. Now that you mentioned it, I realise this might not be a good design. 

Does this cause any problems more than unnecessary nuisance?

**Comment by mooseyboots** [comment]
does that mean it saves once for each note? or 8 times always. i am adding annotations to a book-length file, it could get messy.

**Comment by nobiot** [comment]
Yes, at the moment, every modified annotation in the notes file.

**Comment by mooseyboots** [comment]
hm, i think this happens even when i don't modify notes, but maybe i'm wrong. i'll see next time i'm working.

**Comment by mooseyboots** [comment]
my other thought was maybe this happens when i don't mod a note, but when they get moved as per #34.

**Comment by nobiot** [comment]
With PR #51 just merged, the save behaviour has changed:

1. the notes buffer gets saved per highlight only when you add a highlight
2. the notes buffer gets saved collectively only once when you save the source buffer

This effectively resolve the issue of multiple saves when you have many highlights in the source buffer. 

Thank for reporting the issue (and other contributions). I'm closing this issue now. Please reopen if issue still persists.
