### ISSUE TITLE
remarks get displaced/offset from their word

### ISSUE THREAD

**Issue by mooseyboots** [nobiot/org-remark#34]
as i edit my file, i find my org-remark annotations drift away from what they originally marked.

i have random, unrelated things annotated, and don't know where the annotations belong.

at the moment i don't have any further debug-info about this. if i obtain any i'll report back.

**Comment by nobiot** [comment]
The only reason I can think of is the source file is changed without org-remark mode active. Even a single space added/removed will move the position of highlights. Git might do something. Or some external sync?

**Comment by mooseyboots** [comment]
hm strange. i'll keep playing and see if i can narrow down when it happens.

in my config i run `(org-remark-global-tracking-mode)’, and its var is `t`.

**Comment by nobiot** [comment]
You might auto clear trailing space, perhaps?

**Comment by mooseyboots** [comment]
no.

but how about filling-paragraphs? i fill to avoid performance problems in org. if that does it i wouldn't be able to use `org-remark` at all. :/

**Comment by nobiot** [comment]
how do you call it? I believe it can be used with org-remark. I’d need to try it myself.

**Comment by mooseyboots** [comment]
`fill-paragraph`, bound to `M-q` for me.

but i would think this should be fine as it would only be called while `org-remark` is active.

**Comment by nobiot** [comment]
I tried `fill-paragraph` with `M-q`. There is no problem on my end. I also have my custom function to "undo" fill-paragraph; I can do undo and then fill-paragraph again and again with no problem with the highlights by org-remark.

**Comment by nobiot** [comment]
Closing; not reproducible. If issue persists, please reopen.
