### ISSUE TITLE
if I marked a word ,don't mark it again

### ISSUE THREAD

**Issue by dian-yu-luo** [nobiot/org-remark#35]
Should I execute the function org-remark-mark on a given word, said word shall be marked correspondingly. However, should I execute this function again, the said word will be marked again, which is considered as an undesirable output.
The said word should not be marked twice.
Should I execute another function on the given word, such as (org-remark-delete)
Additionally, if I mark the said word, and delete the mark thereupon, a blank line would appear in marginalia buffer.

**Comment by nobiot** [comment]
What is the case of marking exactly the same word twice for you?

I am thinking like this below:

I have a sentence: "I like Emacs."

First, I mark and highlight the word "Emacs".

Second, I mark the whole sentence and highlight "I like Emacs."

Both should be a highlight. The system should not automatically remove "Emacs" from the second highlight and make it "I like ".

This would mean that the system should check if the second is **exactly** identical with the first.

I'm thinking, the user should avoid marking the word second time. It's an overkill if the system checks this case -- as far as I have seen, e-book reader apps don't do this either.

**Comment by nobiot** [comment]
Closing.
