### ISSUE TITLE
TeX Export Options

### ISSUE THREAD

**Issue by SylvianHemus** [nobiot/org-remark#36]
Cool package, was looking for something like this a year ago. Will try using it for commenting on colleagues papers, annotating sources, and grading papers. 

Are there already some TeX templates for export? e.g., having annotations appear in a colored box or the side window of the main body of text using something like minipage? Do annotations export as pdf annotations?

Personally, I'm not fond of pdf annotations. They are boring and don't show off 1337 skills enough. If they aren't already in this package, I'll probably just design a few TeX templates for different tasks (literate email with org-mime, literate bibliographies, lecture notes, grading ...)

**Comment by nobiot** [comment]
Hi thank you! I don’t export from Org and don’t use TeX myself so there is none. Please do-your-own, PR, or anything that suites your needs :)

**Comment by SylvianHemus** [comment]
Will make my own templates and PR
