### ISSUE TITLE
Highlight, not underline

### ISSUE THREAD

**Issue by AtomicNess123** [nobiot/org-remark#41]
I am not able to highlight, but underline only. Is this the default behaviour?

According to the guidelines to create highlights, this should create a yellow highlight, but I only see an underline:

```
  (org-remark-create "yellow"
                     '(:underline "gold" :background "yellow" :foreground:"black")
                     '(CATEGORY "important"))

```

**Comment by nobiot** [comment]
Works on my end:

![image](https://user-images.githubusercontent.com/12507865/194877521-082f97ec-c7d1-40e5-88bc-6e6fcb38566c.png).

There is an extra colon ":" after ":foreground" in your configuration above, but this didn't seem to affect the result I see.

**Comment by AtomicNess123** [comment]
Thanks, now it worked after removing the colon!
