### ISSUE TITLE
Notes in websites?

### ISSUE THREAD

**Issue by Ypot** [nobiot/org-remark#42]
Could org-remark be used for static web pages?
I think it could be a very useful feature, since it would allow reading and annotating the WWW directly with org-mode.

Maybe it should be useful just for static websites, or it could save a copy of the web page and ask to the user if she wants to reload it?

Inspired by a couple of friendly suggestions:
https://lists.gnu.org/archive/html/emacs-orgmode/2022-10/msg00451.html
https://lists.gnu.org/archive/html/emacs-orgmode/2022-10/msg00442.html

**Comment by nobiot** [comment]
Would this [PR](https://github.com/nobiot/org-remark/pull/27) be of help?

I have been meaning to merge it. My life situation allows me to do it only in late November or December this year

**Comment by Ypot** [comment]
> Would this [PR](https://github.com/nobiot/org-remark/pull/27) be of help?
> 
> I have been meaning to merge it. My life situation allows me to do it only in late November or December this year

That sounds great!
