### ISSUE TITLE
unable to load package on windows

### ISSUE THREAD

**Issue by JonatanSahar** [nobiot/org-remark#62]
Hi, 
I don't reckon it's an actual issue with the package, although I don't have this issue with any other package..
I'm on doom - so I added `org-remark` to the packages file and synced - and I saw that the package was fetched and built, but I can't see any of its functions, and can't `locate-library` it.  I also tried to `M-x package-install` it, but couldn't find it there(??).
I'd appreciate any direction, thanks!

**Comment by nobiot** [comment]
I have never understood how doom works. All I know is this:

1. In ~/.doom.d/package.el
(package! org-remark)
3. doom sync
4. In ~/.doom.d/config.el
(use-package! org-remark
;; other config
)

**Comment by nobiot** [comment]
It is probably quicker tk get meaningful advice on doom’s Discord

**Comment by JonatanSahar** [comment]
Yeah, that's what I have in my config.. very strange.
They've actually been pretty unresponsive the last few times I tried.

**Comment by nobiot** [comment]
If what you say is indeed correct, you should be able to do the following to fix the issue for one session, but this is not the correct doom way.

```
(require 'org-remark)
```

If this does not change anything, then I suspect I don’t understand doom or your doom is not set up correctly.

I cannot help you much more: I am on holidays with no access to Emacs and I don’t use doom.

One thing you could do more is to show your configuration. At the moment, I only know this:

1. you claim you cannot “see any of functions” of a certain package (org-remark)
2. You use doom
3. You claim the package in question is built (how do you know?)
4. You seem to be a beginner of Emacs and doom

This is pretty much it. You usually should tell what step by step (command by command, including cli command if relevant) you have done so far. And your config…

**Comment by nobiot** [comment]
Not sure if this is still an issue now. Closing for now. Let me know if you still cannot load on Doom...
