### ISSUE TITLE
WISHLIST: info-mode support

### ISSUE THREAD

**Issue by scholablade** [nobiot/org-remark#65]
Hey, thanks for the great package, I think it would be nice to use org-remark with info-mode.

**Comment by nobiot** [comment]
I think it is a good idea to explore. I am a bit tied to the next big PR that adds nov.el support (epub ebooks) #58, so I cannot promise when I can have a look.

Alternatively, a PR will be welcome.

**Comment by nobiot** [comment]
@scholablade , the new 1.2.1 version (ELPA being updated) has added info-mode support. Refer to the [Installation section of README](https://github.com/nobiot/org-remark#installation) on how to set it up (no configuration, just activation of the new mode to extend `org-remark-mode`).

**Comment by scholablade** [comment]
Cool, thanks!
