### ISSUE TITLE
 org-remark-notes-display-buffer-action documentation could be more specific

### ISSUE THREAD

**Issue by ouboub** [nobiot/org-remark#67]
Hi

I would like to try out to have the org-remark-window instead of the left margin
either on the top or button and to try to play with its size, however
```
(defcustom org-remark-notes-display-buffer-action
  `((display-buffer-in-side-window)
    (side . left)
    (slot . 1))
  "Buffer display action that Org-remark uses to open marginal notes buffer.
```
does not provide much information how to achieve that.

thanks
Uwe Brauer

**Comment by nobiot** [comment]
Thank you for splitting this issue out. I will come back to it soon.

**Comment by nobiot** [comment]
Firstly, to configure the user option for window size,see the image below and try `window-width` like so:

![Screenshot from 2023-07-20 21-35-40](https://github.com/nobiot/org-remark/assets/12507865/a9546129-4e38-48fd-b6e6-d6e47f1954f3)

You should be able to adjust the value (0.2, 0.25, etc.)
![Screenshot from 2023-07-20 21-35-53](https://github.com/nobiot/org-remark/assets/12507865/4da0f883-6403-46fc-9dfa-18dcbe0c2717)


Secondly, documentation.

I agree that it is not intuitive, so the documentation should be improved. 

- I would like to stick to the name `display-buffer-action`, which is the Emacs standard vocabulary.

- I will look at other packages such as Denote as reference (it has `denote-link-backlinks-display-buffer-action`. Its documentation string is similar to mine, but it also provides a better configuration example and link to Info documentation). 

- I will also consider adding an entry in Org-remark's user manual for this.

**Comment by ouboub** [comment]
> Firstly, to configure the user option for window size,see the image below and try `window-width` like so:
> 
> ![Screenshot from 2023-07-20 21-35-40](https://user-images.githubusercontent.com/12507865/254990597-a9546129-4e38-48fd-b6e6-d6e47f1954f3.png)
> 
> You should be able to adjust the value (0.2, 0.25, etc.) ![Screenshot from 2023-07-20 21-35-53](https://user-images.githubusercontent.com/12507865/254990704-4da0f883-6403-46fc-9dfa-18dcbe0c2717.png)
> 
> Secondly, documentation.
> 
> I agree that it is not intuitive, so the documentation should be improved.
> 
> Currently, the detailed documentation and what values are expected are in the linked documentation of `display-buffer` (you can find the mention of `window-width` among others).
> 
> ![image](https://user-images.githubusercontent.com/12507865/254993609-224d448f-a84e-431a-aada-691ee40f09db.png)
> 
> * I would like to stick to the name `display-buffer-action`, which is the Emacs standard vocabulary.
> * I will look at other packages such as Denote as reference (it has `denote-link-backlinks-display-buffer-action`. Its documentation string is similar to mine, but it also provides a better configuration example and link to Info documentation).
> * I will also consider adding an entry in Org-remark's user manual for this.

thanks, but when I run 
```
(customize-option 'org-remark-notes-display-buffer-action)
```
I do not see the window-with option!!!!

secondly

suppose I don't like to have the notes at the side but prefer at the top or bottom

I can switch to 
```
display-buffer-at-bottom
```

but not to top, do I miss something?

**Comment by nobiot** [comment]
> I do not see the window-with option!!!!

You need to press the `[INS]` button to insert a new blank element to the list.

![Screenshot from 2023-07-21 08-29-33](https://github.com/nobiot/org-remark/assets/12507865/ef81084f-91c3-4a05-a6fe-43975cdfca11)

> suppose I don't like to have the notes at the side but prefer at the top or bottom
suppose I don't like to have the notes at the side but prefer at the top or bottom

You can put a "side-window" to the top or bottom. You can also adjust the height, like so:

![Screenshot from 2023-07-21 08-34-03](https://github.com/nobiot/org-remark/assets/12507865/6b3e451a-a05b-470c-97ea-4a721666c262)

The result should be like this:

![Screenshot from 2023-07-21 08-33-49](https://github.com/nobiot/org-remark/assets/12507865/a2676fef-955e-403a-9d8d-ef7e4b7e0799)

**Comment by ouboub** [comment]
and for the vertical window it would be
window-heigh?

Please add this information to the docstring, this is not obvious at all, thank you

**Comment by ouboub** [comment]
also the logic is odd here the function to be selected is called
display-buffer-in-side-window
symbol is side
but value top

very strange, 

BTW I tried now to and windows heigh but changing the parameter 
to 0.5 or even 1 did not change anyghint

**Comment by nobiot** [comment]
> BTW I tried now to and windows heigh but changing the parameter
> to 0.5 or even 1 did not change anyghint

Can you show me your screen capture?



> also the logic is odd here the function to be selected is called
> display-buffer-in-side-window
> symbol is side
> but value top

This is the Emacs terminology I am following. I will do my best to add more information. Do you have a suggestion for paragraphs to add?

**Comment by ouboub** [comment]
Here is the screenshot
![org-remark-conf](https://github.com/nobiot/org-remark/assets/5957203/493314fe-7eae-4187-a57a-b8d845c82e51)

**Comment by nobiot** [comment]
You have misspelled "window-height”. The last “t” is missing.

**Comment by ouboub** [comment]
oops, I just realised, sorry for the noise
