### ISSUE TITLE
org 9.6.7 breaks `org-remark-highlights-get`

### ISSUE THREAD

**Issue by alan-w-255** [nobiot/org-remark#70]
[f93d855c5106e92f60e6ce99ffde4e72300840e6](https://git.savannah.gnu.org/cgit/emacs/org-mode.git/commit/?h=release_9.6.7&id=f93d855c5106e92f60e6ce99ffde4e72300840e6)

https://github.com/nobiot/org-remark/blob/5cd59e70ef2e52a83079952d28a787b95fe775c7/org-remark.el#L1360C36-L1360C36

`(forward-line 0)` return 0 instead of nil. It cause org-remark highlight not works with org-mode 9.6.7.

**Comment by nobiot** [comment]
Thank you for reporting this. I didn't know. I patched the code. I am not on Org version 9.6.7. Would you mind testing it by any chance?

**Comment by nobiot** [comment]
On 9.6.6, It was OK. It should work for the next release with the change you reported.

**Comment by alan-w-255** [comment]
Thank you so much for this prompt fix and your awesome  package.

I have just tested the latest code and it successfully resolved the problem I was encountering.

**Comment by nobiot** [comment]
Thank you for confirming!
