### ISSUE TITLE
[feature request] make org-remark-open open the associated marginalia file if pointer not inside a highlight

### ISSUE THREAD

**Issue by oatmealm** [nobiot/org-remark#72]
Thought it'd be useful if `org-remark-open` will open the default marginalia file associated with the file being currently edited.

**Comment by nobiot** [comment]
I like the idea of being able to open the marginalia file from the file I am editing. I often find myself wanting to do this.

Evaluating this seems to does the job: `(find-file (org-remark-notes-get-file-name))`.

I will see if I can find some time and add it to `org-remark-open` -- I think we will need to see if adding the feature in this function is the best way for the user interaction. I was originally thinking of having a separate function to open the file from within the `*marginalia*` buffer.

Your idea seems to be better than my original intuition.

**Comment by oatmealm** [comment]
I was indeed thinking if there's noting at point then simply open the default notes file associated.

**Comment by nobiot** [comment]
Sure. I got this in my local and testing. There are some issues I need to deal with that I had't anticipated.

**Comment by oatmealm** [comment]
I guess it should be a *dwim type of a function, that does either depending on the context... ?

**Comment by nobiot** [comment]
Yes, that's the idea and what I have in my local.

It's now part of the branch `dev/1.3.0` (PR #71). v1.3.0 will come with a whole new type of highlights: line-highlights. So `org-remark-open` does "do-what-i-mean" (dwim) based on the context where the cursor is.

You can try out the v1.3.0 from the dev branch, if you like. I am probably a few weekends away to document the new features. 

Your query has motivated me, so I might do a quick write-up and merge the dev branch to main sooner than "a few weekends". Thank you!

**Comment by nobiot** [comment]
Now this feature is merged to main and available in GNU-devel ELPA. I'll wait for a few weeks/months and then bump the version to make the new features available in GNU ELPA. 

I'm closing this issue now; let me know if you have any issues, questions, etc. Thank you.
