### ISSUE TITLE
Wrong command name `org-remark-line-alt' in manual

### ISSUE THREAD

**Issue by qingshuizheng** [nobiot/org-remark#73]
Hello nobiot, 

https://github.com/nobiot/org-remark/blob/5dca4744d42c1b17ff0bf94bae0114f089e807bb/docs/org-remark.org?plain=1#L248C42-L248C62

> ;; This creates a custom command named org-remark-line-alt.

Here the custom command name should be `org-remark-mark-line-alt' ?

**Comment by nobiot** [comment]
Oh very quick! I think you are right. Let me double check after a good night sleep and fix the documentation. Thank you!

**Comment by nobiot** [comment]
Fixed. Thanks for your quick report.
