### ISSUE TITLE
Bug: Error during save if source-buffer is narrowed (args out of range)

### ISSUE THREAD

**Issue by akashpal-21** [nobiot/org-remark#83]
During save - if the source-buffer in question is narrowed - then the `org-remark-highlights-adjust-positions` function which runs during this time -- probably re initiating all the highlights - fails to check the `when `condition that is there to evaluate whether "original text exists AND it is different to the current text" .

Two ways to avoid the problem

Approach one

```
(defun org-remark-highlights-adjust-positions (overlays _notes-buf)
  "Run dolist and delgate the actual adjustment to another function.

OVERLAYS are highlights.

Check the original text property exits and not the same as the
current highlighted text.

Meant to be set to `org-remark-highlights-after-load-functions' by mode-specific
extensions."
  (dolist (ov overlays)
    (let ((highlight-text (overlay-get ov '*org-remark-original-text)))
      ;; Check that the original text exists AND it is different to the
      ;; current text
      (when
          (and (org-remark-highlights-adjust-positions-p (overlay-get ov 'org-remark-type))
               highlight-text
               (not (org-remark-string=
                     highlight-text
		     ;; HHHH---------------------------------------------------
		     (when (eq major-mode 'org-mode)
		       (org-with-wide-buffer (buffer-substring-no-properties
					      (overlay-start ov) (overlay-end ov))))
		     ;; (buffer-substring-no-properties
		     ;; (overlay-start ov) (overlay-end ov))
		     ;; HHHH---------------------------------------------------
		     )))
        (org-remark-highlight-adjust-position-after-load
         ov highlight-text)))))
```

Since the error occurs during `(buffer-substring-no-properties    (overlay-start ov) (overlay-end ov))` we may run this within `(org-with-wide-buffer`

The second approach that I have discovered is changing the after-save-hook

```
(defun org-remark-save ()
  "Save all the highlights tracked in current buffer to notes buffer.

This function is automatically called when you save the current
buffer via `after-save-hook'.

`org-remark-highlights' is the local variable that tracks every highlight
in the current buffer.  Each highlight is an overlay."
  (interactive)
  (org-remark-highlights-housekeep)
  (org-remark-highlights-sort)
  (let ((notes-buf (find-file-noselect (org-remark-notes-get-file-name)))
        (source-buf (or (buffer-base-buffer) (current-buffer))))
    (dolist (h org-remark-highlights)
      (org-remark-highlight-add h source-buf notes-buf))
    ;;; Avoid saving the notes buffer if it is the same as the source buffer
    (if (eq source-buf notes-buf)
        (set-buffer-modified-p nil)
      
;; HHHH---------------------------------------------------
      (with-current-buffer source-buf
	(org-with-wide-buffer
;; HHHH---------------------------------------------------
	 (with-current-buffer notes-buf
           (save-buffer)))))))
 ```
 
 
 The error in question is as follows

```
Saving file /home/akash/roam/test.org...
Wrote /home/akash/roam/test.org
Saving file /home/akash/roam/resources/test/notes.org...
Wrote /home/akash/roam/resources/test/notes.org
Org-remark: error during loading highlights: (args-out-of-range #<buffer test.org> 110 119)
```

Thank you.

**Comment by nobiot** [comment]
> Do you think pushing something like this would be alright?

Yes, what you are proposing looks fine. What’s your concern?

I need someone (me included) to repro the issue and test your solution. It is possible that there is a better place to put save-restriction ans widen — I would have thought I’d already placed them but that’s not the case from this issue :)

**Comment by nobiot** [comment]
I cannot narrow an org buffer before highlights are added to the entire buffer because I use "global tracking". 

How do you get to this situation?

**Comment by nobiot** [comment]
Thanks for additional detail... I will look, but let me have some time. On vacation in a remote place :)

**Comment by nobiot** [comment]
Looks like I should have used a PR to send this commit [d37ec06](https://github.com/nobiot/org-remark/commit/d37ec06547d28b8e7e039aeef333a93d0dfba1a3) but it is meant to fix the issue of `:org-remark-link: gets wrongly referenced`.

Thank you @akashpal-21 for staying with me on this one. I believe it's fixed. Please open it again if it is not with the commit.
