### ISSUE TITLE
[feature request] Create the marginal notes file upon first entry

### ISSUE THREAD

**Issue by hkjels** [nobiot/org-remark#84]
I would like to keep `org-remark` on for all buffers that have an associated file, globally. However that creates a lot of empty marginal note files. I'm thinking, instead of creating the file when the mode is enabled, it would be a better to create it along with the first entry.

```emacs-lisp
(use-package org-remark
  :blackout " remark"
  :commands (org-remark-mode)
  :hook (after-change-major-mode . org-remark-enable)
  :config
  (defun org-remark-enable ()
    (when buffer-file-name
      (org-remark-mode 1))))
```

This is currently how I enable `org-remark` to have the lighter-menu available all over the place.

**Comment by nobiot** [comment]
> instead of creating the file when the mode is enabled, it would be a better to create it along with the first entry.

This is what `org-remark-global-tracking-mode` is meant to do. Do you use it? It's part of the user manual and README for configuration suggestion.

**Comment by hkjels** [comment]
I missed that. I'm sorry.
Thank you!

**Comment by nobiot** [comment]
@hkjels No need to be sorry, please. More importantly, does it work as you expect it to?

**Comment by hkjels** [comment]
Looks like it does 👍🏻

**Comment by nobiot** [comment]
Okay, thanks foe confirming
