### ISSUE TITLE
"No highlights or annotations found for" all the time

### ISSUE THREAD

**Issue by greg-minshall** [nobiot/org-remark#85]
hi.  i'm a new user.  i've installed and iniitialized org-remark as suggested (on the web page and in the info pages).  i'm getting a lot of this message, i guess every time i enter a new Info node.

````
No highlights or annotations found for ...
````

would it be possible to turn them off?  they seem to be coming from `org-remark-highlights-get`, looking, i assume, for any highlights ("or annotations") for that node.  but, given that 99.99% of nodes don't have any such, it doesn't seem like something i will care about.  and, it erases other messages that might be in the minibuffer, fills up `*Messages*`, etc.

cheers.

**Comment by nobiot** [comment]
There is no user option currently. The easiest is to delete the line in the program directly. 

I will consider this in the next iteration, but I have no immediately plan to work on it so I can’t say when.

Alternatively, I will also welcome a PR.

**Comment by greg-minshall** [comment]
thanks!
